Saurav/nightly updates
Conv-AI/Convai-Web-SDK-Old pull request #2
Opened 2023-10-23 12:48 UTC by AirSurfer09

generate Audio config added

2023-10-25 08:58 UTC, crazylazylife reviewed
We do not need the "Proto/service" folder outside "dist". Can you remove that. I do not think it was there originally.

2023-10-25 08:58 UTC, crazylazylife commented on .gitignore
> +CharacterUtil.js
Can you make it a part of the src folder.

2023-10-26 10:08 UTC, manni901 requested changes

2023-10-26 10:08 UTC, manni901 commented on Proto/service/service.proto
> +    }
This is not the latest proto. Please get it from Yash.

2023-10-26 10:08 UTC, manni901 commented on Proto/service/service_pb2.py
Remove this file.

2023-10-26 10:08 UTC, manni901 commented on Proto/service/service_pb2_grpc.py
Remove this file.

2023-10-26 10:22 UTC, AirSurfer09 commented on Proto/service/service.proto
> +    }
Will be updated with lipsync integration

2023-10-26 10:22 UTC, AirSurfer09 commented on Proto/service/service_pb2_grpc.py
Have deleted the file : https://github.com/Conv-AI/Convai-Web-SDK/pull/2/commits/4686caf10034b8e5a9d8146f6fe9f9680f74fb88

2023-10-26 10:22 UTC, AirSurfer09 commented on Proto/service/service_pb2.py
Have deleted the file : https://github.com/Conv-AI/Convai-Web-SDK/pull/2/commits/4686caf10034b8e5a9d8146f6fe9f9680f74fb88

2023-10-26 11:37 UTC, manni901 approved these changes

2023-10-26 11:37 UTC, manni901 commented on .gitignore
> +Proto/service/service_pb2_grpc.py
Remove this. These files should not be in the repository at all.

2023-10-27 13:14 UTC, crazylazylife approved these changes

2023-10-27 13:14 UTC, merged